### ISSUE TITLE
Does This Library Work?

### ISSUE THREAD

**Issue by adonig** [NaridaL/chroma.ts#1]
I tried using it in my Stencil.js project (Typescript + Rollup), but I keep getting those errors during build:

<img width="885" alt="Screen Shot 2020-01-28 at 12 09 43" src="https://user-images.githubusercontent.com/900404/73259043-39120100-41c7-11ea-8284-f572a8b684f3.png">

When I open index.d.ts from chroma.ts I see those red lines:

<img width="1440" alt="Screen Shot 2020-01-28 at 12 12 49" src="https://user-images.githubusercontent.com/900404/73259237-97d77a80-41c7-11ea-9daa-7b9919fa5ade.png">

I think there is no symbol `blend_f` in the index.ts either: https://github.com/NaridaL/chroma.ts/blob/master/src/index.ts

So, does this library work, or is it better to stick with chroma.js? :-)

**Comment by NaridaL** [comment]
Hey @adonig , yeah there seems to be a glitch in the types generation. There's no error in the sources. You can suppress errors in .d.ts files in dependencies by adding `"skipLibCheck": true` to your tsconfig.json.

I will have a look later to try and fix the errors in the types.

**Comment by NaridaL** [comment]
@adonig I published 1.0.8, which should fix the errors. Please close the issue if it does. 😄

**Comment by adonig** [comment]
@NaridaL Works like a charm! Thank you very much! 🙏
